### ISSUE TITLE
Serverside - Server Tick Loop Crash

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Hugman76/Mubble#21]
**Describe the bug**
Putting the mod on a server crashes upon starting

**Expected behavior**
It should normally start.

**Links**:
https://gist.github.com/P3rf3ctXZer0/c44cc39d01a32b8ae5311de60e1997f6

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug has been fixed in v**1.2.1**.

**Comment by Hugman76** [comment]
### Oops!
The bug seems to still happen in v**1.2.1**.

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug has been fixed in v**1.2.2**.
