### ISSUE TITLE
Crash on world creation (1.13.2)

### ISSUE THREAD

**Issue by SDUBZ** [Hugman76/Mubble#33]
minecraft: 1.13.2
Forge: 1.13.2-209
mubble: Mubble-1.4-pre7-(1.13.2)

**Describe the bug**
created a new world with mod and game crashes

**To Reproduce**
1.create new world
2.start generating 
3. See error

**Expected behavior**
Start a new world and have fun yayy

debug log:
[debug.log](https://github.com/Hugman76/Mubble/files/3175938/debug.log)

**Comment by Hugman76** [comment]
Hello there, have you tried downgrading your Forge version to 25.0.110? This is the recommended version to play in with Mubble at the moment, as said on the [project page](https://minecraft.curseforge.com/projects/mubble/files/2697637).

**Comment by SDUBZ** [comment]
so many mods are asking for 191+

**Comment by Hugman76** [comment]
### Thanks for the report!
However, this bug isn't a bug, in fact, this is a feature and properly works as intended.
