### ISSUE TITLE
Palm Sapling doesn't disappear upon growing

### ISSUE THREAD

**Issue by Sven792** [Hugman76/Mubble#46]
**Mubble Version:** 1.4-pre9 or the latest build

**Describe the bug**
The palm sapling will not be replaced by a palm log or the tree will be generated one block over the sapling.

**To Reproduce**
1. Place a palm sapling and wait until it grows or use bone meal.
2. When it has grown, you will see that the block on the ground is still a sapling.

**Expected behavior**
The sapling usually disappears, if the palm tree is fully grown.

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug has been fixed in v**1.4**.
