### ISSUE TITLE
All or most blocks that should burn are not burnable

### ISSUE THREAD

**Issue by Sven792** [Hugman76/Mubble#47]
**Mubble Version:** 1.4-pre9 or the newest build

**Describe the bug**
All or most blocks that should burn e.g. Wooden Stairs are not burnable or not disappear after that.

**To Reproduce**
1. Place a Wooden Stair or other things that should burn from Mubble.
2. Lit it up with flint and steel.
3. See the result.

**Expected behavior**
The 'burnable blocks' should burn and disappear.

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug has been fixed in v**1.4**.

![image](https://user-images.githubusercontent.com/36963654/66273217-4438ce00-e872-11e9-96b9-6ae035003663.png)
