### ISSUE TITLE
Implement Stonecutter Recipes

### ISSUE THREAD

**Issue by WenXin20** [Hugman76/Mubble#48]
**Describe the bug**
Currently it is not possible to craft the different stone block stairs and slabs from their respective blocks in the Stonecutter.

**To Reproduce**
1. Place a stonecutter
2. Place Carbonite or other stone in the input slot

**Expected behavior**
It would be nice to be able to craft stairs, slabs, etc. in the stonecutter.

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug has been fixed in v**1.4**. I successfully added stonecutting recipes for 176 items.

![image](https://user-images.githubusercontent.com/36963654/66267294-69f0b380-e82f-11e9-8529-c3bce0324752.png)
