### ISSUE TITLE
Inner Seams of Tetris Glass should be Invisible

### ISSUE THREAD

**Issue by WenXin20** [Hugman76/Mubble#49]
**Describe the bug**
Currently in Minecraft 1.14.4, if Tetris Glass is placed next to each other, the inner seams will still render, which looks pretty odd. 
It also renders incorrectly underwater.

**To Reproduce**
1. Get some Tetris Glass
2. Place several next to each other

**Expected behavior**
Tetris Glass should instead render similarily to Vanilla Minecraft Glass.

![2019-10-28_18 18 00](https://user-images.githubusercontent.com/12000593/67725152-50b2d100-f9af-11e9-89de-430abc63e559.png)

![2019-10-28_18 20 31](https://user-images.githubusercontent.com/12000593/67725238-a7200f80-f9af-11e9-9f04-d98001078dd7.png)

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug has been fixed in the next update.
