### ISSUE TITLE
Costumes make the server receive client information

### ISSUE THREAD

**Issue by somario360** [Hugman76/Mubble#51]
**Describe the bug**
When putting on a costume that give effects while on a server, it will instantly kick you until the player's inventory is cleared. This is happening because the server is trying to render shaders, which is something that only exists on the client side.

**To Reproduce**
1. Equip a costume that gives shader effects
2. It will kick you

**Logs**
[2019-11-26-1.log](https://github.com/Hugman76/Mubble/files/3898373/2019-11-26-1.log)

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug will be fixed for v**2.0.1**.
