### ISSUE TITLE
Flowers & saplings can't be placed in flower pots

### ISSUE THREAD

**Issue by WenXin20** [Hugman76/Mubble#53]
**Describe the bug**

`Minecraft v1.14.4`
`Mubble v2.1`
`Forge v28.1.109`

Mubble flowers & saplings cannot be placed in flower pots.

**To Reproduce**
1. Place a flower pot
2. Try to right-clicking a sapling or flower on the flower pot.

**Expected behavior**
Right-clicking the flower pot with Mubble flowers & saplings should've created the corresponding potted plants.

As requested :)

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug will be fixed for the next version.
