### ISSUE TITLE
Stomping Goombas is too difficult

### ISSUE THREAD

**Issue by joelwarior** [Hugman76/Mubble#58]
**Describe the bug**
Stomping Goombas is too difficult 

**To Reproduce**
1. Summon a goomba
2. Try to jump on it
3. Repeat multiple times

**Comment by Hugman76** [comment]
Hi joelwarior! Could you please provide more information? Apparently it sounds like you find stomping goombas being a difficult task. This is being worked on for the next update.

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug has been fixed for the next version.

**Comment by joelwarior** [comment]
ou pouvons nous envoyr les suggestions

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
