### ISSUE TITLE
2 sounds are unused

### ISSUE THREAD

**Issue by Hugman76** [Hugman76/Mubble#6]
**Describe the bug**
There are 2 sounds completely introduced, that can be played via the `/playsound` command that aren't unused anywhere:
- [`block.empty_block.hit`](https://github.com/Hugman76/Mubble/blob/master/resources/assets/mubble/sounds/block/empty_block.hit.ogg)
- [`brick_block.break`](https://github.com/Hugman76/Mubble/blob/master/resources/assets/mubble/sounds/block/brick_block.break.ogg)

**Expected behavior**
The `block.empty_block.hit` sound should be used when an Empty Block breaks and the `brick_block.break` sound should be used when a Brick Block or a Golden Brick Block breaks.

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug has been fixed in v**1.1**.

**Comment by FVbico** [comment]
just to make sure, these sound events have the mumble namespace, correct? :)

**Comment by Hugman76** [comment]
Yes, as [`sounds.json`](https://github.com/Hugman76/Mubble/blob/master/resources/assets/mubble/sounds.json) tells.
