### ISSUE TITLE
Feature Requirement - Seperate Project Repository Used on Twitch

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Hugman76/Mubble#67]
**Describe the bug**
Twitch cannot differentiate file styles between fabric and forge so it falsely assumes there is an update. As a modpack manager this is aweful!

**To Reproduce**
Make a project.
Name it.
Make a zip made for forge
Make a zip made for fabric
Only latest can be seen.

**Expected behavior**
Making two seperate project pages. Example 
* Mubble Forge
* Mubble Fabric

![image](https://user-images.githubusercontent.com/10351221/84763199-70742500-af91-11ea-9ef1-86026979e93f.png)
 Example of what users see.

**Comment by Hugman76** [comment]
Hey! I've managed to split Forge and Fabric into two CurseForge projects. Is it better like this?
https://www.curseforge.com/minecraft/mc-mods/mubble
https://www.curseforge.com/minecraft/mc-mods/mubble-fabric
Please also note that the Fabric page needs to be approved by the team before being able to view it.

**Comment by P3rf3ctXZer0** [comment]
Yes thank you so much :D now if I can get vazkii to the same thing the mod world will once again be in balance.
