### ISSUE TITLE
crash with optifabric

### ISSUE THREAD

**Issue by usernameeeeeeeeeeeeee** [Hugman76/Mubble#68]
it crashes with optifabric

**Comment by FVbico** [comment]
Just saying, crash reports are always useful.

**Comment by usernameeeeeeeeeeeeee** [comment]
> Just saying, crash reports are always useful.

there is no crash report

**Comment by Yanis48** [comment]
OptiFabric is no longer a supported mod, so I doubt we'll bother to resolve this conflict

**Comment by usernameeeeeeeeeeeeee** [comment]
> OptiFabric is no longer a supported mod, so I doubt we'll bother to resolve this conflict

please make it not crash

**Comment by Yanis48** [comment]
I'm not the developer of OptiFabric, and there are alternatives to OptiFine available on Fabric: https://gist.github.com/modmuss50/deff1658c4550ca8b16cb5d40ceaa468

**Comment by Yanis48** [comment]
Also the main issue with OptiFine is nobody but its author knows what parts of the code it modifies, so it's hard to make our mods compatible with it
