### ISSUE TITLE
Advancements are not translated

### ISSUE THREAD

**Issue by Hugman76** [Hugman76/Mubble#8]
**Describe the bug**
The 4 new advancements introduced in the Mubble tab are always in English (`en_us`)

**To Reproduce**
1. Get one of these advancements with a supported language other than English.
2. See that they are in English.

**Expected behavior**
The advancements should have been translated in each `.lang` file.

**Comment by FVbico** [comment]
Fixed for dutch v1.2 (I assume)

**Comment by Hugman76** [comment]
Fixed for French and LOLCAT

**Comment by 22zhuyansong** [comment]
Fixed for Chinese.

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug has been fixed in v**1.1.1**.
